### ISSUE TITLE
improve status handling

### ISSUE THREAD

**Issue by lburgazzoli** [bf2fc6cc711aee1a0c2a/cos-fleet-manager#1]
I've been working on improving how the status of individual connectors is reported by the `cos-fleetshard` to the `cos-fleet-manager` and things are working much better now but there is an issue when reporting in progress actions as we do not have a way to report that something is ongoing.

Inspired by a comment from @davidffrench on the [ADR-00052 Connector Service: Control and Data Plane Interactions
](https://docs.google.com/document/d/1FF5naYhR_dNNXjJWh0mRmzhte0ksld56F9MGmG3vGSw/edit?disco=AAAANLRgaZc) I was thinking about using conditions to express ongoing actions.

As today, the `conditions` object in the `ConnectorDeploymentStatus` is ignored by the `cos-fleet-manager` and it is meant to include `conditions`  extracted from the operands CRs but we could instead have a well defined set of condition we can use to have a fine grained reporting of the status.

As example:

```yaml
# phase will be empty until the condition with type DesiredStatusReached
# has status 'True' and no error are reported
phase: "..."
# condition of the top level resource, reports an aggregate overview 
# of the connector status (i.e. it does not reflect the individual
# status of processing units)
conditions:
    - # Name of the condition.
      type: DesiredStatusReached
      # Indicates whether that condition is applicable
      status: True|False
      # Machine-readable, UpperCamelCase text indicating the reason 
      # for the condition's last transition
      reason: "..."
      # Human-readable message indicating details about the last 
      # status transitio
      reason: "..."
```

Conditions can also be shown to the user to have some insight about what's going on.
